#!/bin/sh

echo "Running static analysis..."

# Format code using KtLint, then run Detekt and KtLint static analysis
./gradlew ktlintFormat ktlintCheck detekt --daemon

status=$?

if [ "$status" = 0 ] ; then
    echo "Static analysis found no problems."
    exit 0
else
    echo 1>&2 "Static analysis found violations it could not fix."
    echo 1>&2 "You can use the option --no-verify in commits to bypass this hook (although this is not recommended)"
    exit 1
fi